<a href="https://colab.research.google.com/github/kirtika45/ML-AI/blob/main/MLR_polynomialRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Model Implementation Regression using Polynomial Regression**

In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [53]:
dataset = pd.read_excel('model_selection_rergession.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [54]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [55]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [56]:
y = y.reshape(len(y),1)

In [7]:
print(y)

[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


In [57]:
dataset.describe()

Ambient Temperature  Exhaust Vacuum  Ambient Pressure  \
count          9568.000000     9568.000000       9568.000000   
mean             19.651231       54.305804       1013.259078   
std               7.452473       12.707893          5.938784   
min               1.810000       25.360000        992.890000   
25%              13.510000       41.740000       1009.100000   
50%              20.345000       52.080000       1012.940000   
75%              25.720000       66.540000       1017.260000   
max              37.110000       81.560000       1033.300000   

       Relative Humidity  electrical energy output  
count        9568.000000               9568.000000  
mean           73.308978                454.365009  
std            14.600269                 17.066995  
min            25.560000                420.260000  
25%            63.327500                439.750000  
50%            74.975000                451.550000  
75%            84.830000                468.430000  
max           100.160000                495.760000

In [58]:
dataset.describe().isnull()

Ambient Temperature  Exhaust Vacuum  Ambient Pressure  \
count                False           False             False   
mean                 False           False             False   
std                  False           False             False   
min                  False           False             False   
25%                  False           False             False   
50%                  False           False             False   
75%                  False           False             False   
max                  False           False             False   

       Relative Humidity  electrical energy output  
count              False                     False  
mean               False                     False  
std                False                     False  
min                False                     False  
25%                False                     False  
50%                False                     False  
75%                False                     False  
max                False                     False

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [60]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

In [61]:
print(X_poly)

[[1.00000000e+00 1.12200000e+01 4.31300000e+01 ... 6.77242028e+09
  5.38603280e+08 4.28345379e+07]
 [1.00000000e+00 1.36700000e+01 5.43000000e+01 ... 5.87072958e+09
  4.35831980e+08 3.23553508e+07]
 [1.00000000e+00 3.28400000e+01 7.79500000e+01 ... 2.15967876e+09
  9.74822477e+07 4.40009357e+06]
 ...
 [1.00000000e+00 1.68100000e+01 3.85200000e+01 ... 5.86500714e+09
  4.33197009e+08 3.19964912e+07]
 [1.00000000e+00 1.28000000e+01 4.11600000e+01 ... 7.76570573e+09
  6.54642544e+08 5.51858229e+07]
 [1.00000000e+00 3.23200000e+01 6.79000000e+01 ... 1.45623249e+09
  5.49010997e+07 2.06981424e+06]]


In [63]:
y_pred = regressor.predict(poly_reg.transform(X_test))

In [64]:
np.printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[434.16344109 431.23      ]
 [458.25858821 460.01      ]
 [460.71802838 461.14      ]
 ...
 [469.48757472 473.26      ]
 [438.52951737 438.        ]
 [461.62183057 463.28      ]]


In [65]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9455261540927579